<?php

class RestController extends Zend_Controller_Action
{


    public function preDispatch()
    {
        $this->_helper->layout()->disableLayout();
        $this->_helper->viewRenderer->setNoRender(true);
        parent::preDispatch(); // TODO: Change the autogenerated stub
    }


    public function indexAction()
    {

        //TBD authenticate
        $APICall=$this->getRequest()->getParam('APICall');

        if(!method_exists($this,$APICall)) return $this->sendJSONResponse(false,['error'=>'Appel inconnu']);


       $this->{$APICall}();
        //   parent::indexAction(); // TODO: Change the autogenerated stub
    }





public function getTeams(){


        $mapper = new Default_Model_B2cTeamsMapper();

        $results = $mapper->fetchAll();
    return $this->sendJSONResponse(true,$results);

}



    public function getAllUsers(){



     $usersMapper=new Default_Model_TournoiMapper();

        $sql = "select * from " . $usersMapper->getDbTable ()->__get ( '_name' ). " where update_date like '%".strftime('%Y')."%'"; //
        $results=$usersMapper->execQuery($sql);


    return $this->sendJSONResponse(true,$results);



    }

    public function dorequestAction(){
echo "ok";

$type=$this->_request->getParam('type');
if($this->getRequest()->isPut()) {

    $body = $this->getRequest()->getRawBody();
    $data = Zend_Json::decode($body);

    var_dump($data);
    die();

}

    }

    public function getPoules(){

        $mapper = new Default_Model_B2cPouleMapper();

        $results = $mapper->fetchAll();
        return $this->sendJSONResponse(true,$results);




    }

    private function sendJSONResponse($success=true, array $results=[]){

        $data=['success'=>$success,'data'=>$results];

        $response = new \Zend\Diactoros\Response\JsonResponse($data);

        $emitter = new Zend\Diactoros\Response\SapiEmitter();
        $emitter->emit($response);
        die();



    }


}

?>
