<?php
/**
 * Created by PhpStorm.
 * User: Tcho
 * Date: 07/06/2018
 * Time: 10:30
 */
//<include_once($_SERVER['DOCUMENT_ROOT'].'/../vendor/autoload.php');
class TournoiController extends Zend_Controller_Action
{

    public function init()
    {

        $detect = new Mobile_Detect;

        $this->isMobile= $detect->isMobile() && !$detect->isTablet();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function preDispatch()
    {
        $this->view->headMeta ()->appendHttpEquiv ( 'Content-Type', 'text/html; charset=UTF-8' )->appendHttpEquiv ( 'Content-Language', 'fr-FR' );
        $this->view->headLink ()->appendStylesheet ( '//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' );
        $this->view->headScript ()->appendFile ( '//code.jquery.com/jquery-3.2.1.slim.min.js' )
            ->appendFile ( '//cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js' )
            ->appendFile ( '//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js' );

        $this->_helper->layout->setLayout('tournoi'.($this->isMobile?"-mobile":""));

        parent::preDispatch(); // TODO: Change the autogenerated stub
    }

    public function indexAction(){}


    public function showteamAction(){

        $id_team=$this->getRequest()->getParam('id_team');


        $teamMapper = new Default_Model_B2cTeamsMapper();

        if(!$team=$teamMapper->find($id_team)) die('equipe introuvable');


        $playersMapper = new Default_Model_TournoiMapper();
        $players =$playersMapper->fetchAll('id_team='.$id_team);

        $this->view->headLink()->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css')->appendStylesheet('http://bornestocatch.dahultimate.com/_css/styles.css');
        $this->_helper->layout->setLayout('tournoi-team');
        $this->view->assign(['team'=>$team,'players'=>$players]);

        $this->render("team");




    }




    public function showmatchsAction(){


        $viewdata=[];

        $matchsMapper = new Default_Model_B2cMatchsMapper();
        $matchs=$matchsMapper->fetchAll('date="2018-08-18"');

        usort($matchs, function($a, $b){

            return new DateTime($a['debut'])>new DateTime($b['debut'])?1:-1;

        });


        $viewdata['2018-08-18']=$matchs;

        $matchs2=$matchsMapper->fetchAll('date="2018-08-19"');

        usort($matchs2, function($a, $b){


            return new DateTime($a['debut'])>new DateTime($b['debut'])?1:-1;

        });

        $viewdata['2018-08-19']=$matchs2;

        $this->view->headLink()->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css')->appendStylesheet('http://bornestocatch.dahultimate.com/_css/styles.css');
        $this->_helper->layout->setLayout('tournoi-team');
        $this->view->assign('data',$viewdata);

        $this->render("matchs");


    }



}