
	<h2>Le &laquo; Bornes to Catch &raquo;, cela t'interpelle ?</h2>
	<p><strong>Bonjour, ami(e) !</strong><br />
	J'esp&egrave;re que tu vas bien<br />
        Les Dahultimate sont fiers de te pr&eacute;senter la troisi&egrave;me &eacute;dition de leur d&eacute;sormais c&eacute;l&egrave;bre tournoi 100% de la Haute-Savoie, le <strong>Bornes to Catch</strong> qui aura lieu le week-end du 18/19 ao&ucirc;t 2018.<br />
	Viens t'enivrer de la douceur de l'&eacute;t&eacute; au c&oelig;ur de nos belles montagnes et au milieu des pr&eacute;s, et participe &agrave; la nouvelle &eacute;dition de notre tournoi <em>&laquo; Chapeau &raquo;</em>.
	<br />Qu'importe ton niveau, rejoins-nous, et sois tranquille, nous saurons te recevoir dans la plus pure tradition de l'hospitalit&eacute; savoyarde ! 
	<br /><br />
        <strong>Nous avons tenu compte de toutes les remarques faites sur l'&eacute;dition 2016, ce tournoi n'en sera donc que meilleur !</strong>
	</p>
	<p class="text-center">
        <img src="/medias/btc-2017.jpg" class="img-responsive" alt="" />
        </p>
	<div class="col-md-8 col-xs-12" style="padding-left:0">
	<h3>O&ugrave; auront lieu les festivit&eacute;s ?</h3>
	<p>
	Le tournoi aura lieu &agrave; Saint-Ferreol, au pied du massif des Bornes, au bout du lac d'Annecy.<br />Tu n'as rien d'autre &agrave; faire que de venir et de l&acirc;cher prise !<br />
	En effet, toutes les infrastructures (terrains, camping et salle des f&ecirc;tes) se trouvent &agrave; port&eacute;e de main.
	<br />C'est super, n'est-ce pas ?<br />
	Tu auras tout loisir de faire la f&ecirc;te et de rentrer en toute s&eacute;r&eacute;nit&eacute; vers ta tente sans crainte de la mar&eacute;chauss&eacute;e.
	<br />Tu peux aussi profiter du cadre idyllique pour emmener ta petite famille profiter de l'air vivifiant de nos montagnes.<br />  
	</p>

	<h3>Formule</h3>
	<ul class="list-group col-md-6 col-xs-12">
		<li class="list-group-item">Tournoi <em>&laquo; Chapeau &raquo;</em> en loose coed</li>
		<li class="list-group-item">8 &eacute;quipes</li>
		<li class="list-group-item">2 poules de 4 le premier jour sur deux terrains</li>
		<li class="list-group-item">des matchs de classements le dimanche</li>
	</ul>
	<div class="clearfix"></div>
	<h3>Quel est le co&ucirc;t de cet &eacutev&egrave;nement ?</h3>

	
	<ul class="list-group col-md-6 col-xs-12">
	 <li class="list-group-item active"><strong>Formule "tout compris" (hors boissons) <?php echo PRIX_JOUEUR?> &euro; incluant :</strong></li>
	 <li class="list-group-item">La soir&eacute;e de bienvenue avec son pot de l'amiti&eacute; et de quoi sustenter ton app&eacute;tit</li>
	 <li class="list-group-item">Le petit d&eacute;jeuner du samedi et du dimanche  </li>
	 <li class="list-group-item">Le d&eacute;jeuner du samedi et du dimanche </li>
	 <li class="list-group-item">L'ap&eacute;ro pack du samedi soir </li>
	 <li class="list-group-item">Le repas savoyard du samedi soir </li>
	 <li class="list-group-item">... et plein de surprises </li>
	
	</ul>
<div class="clearfix"></div>
	
	<p>
	Tu peux, &agrave; ta convenance, venir accompagn&eacute; ou en tant qu'invit&eacute; pour t'amuser avec nous, il ne t'en co&ucirc;tera que <?php echo PRIX_NONJOUEUR?> &euro; comprenant presque tout ce qui est list&eacute; ci-dessus.<br />
	Les enfants sont bienvenus, &agrave; un  petit prix de <?php echo PRIX_ENFANT?> &euro;. 
	
	
	</p>
	
	<div class="clearfix"></div>
	
	</div>
	
	<div class="col-md-4 col-xs-12 img-thumbnail">
	
	<?php  echo $this->partial('index/map.phtml');?>
	
	
	</div>
	<div class="clearfix"></div>
	<p>
            <strong>Si tu as encore une h&eacute;sitation, prends le temps de compulser l'album de l'ann&eacute;e derni&egrave;re c'est <a style="color:#9b1a15" href="<?php echo BTC_PHOTO_LINK ?>" target="_blank"><em class="fa fa-picture-o"></em> ici</a>.</strong>
    </p>
    <p>
<strong>Encore un doute ?</strong>

    </p>
    <div class="col-md-6">
        <em>L'universe point de la finale 2017.</em>
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/P9u8NpPehYk?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
        </div>
        <small>&copy; Clément Quartier</small>

    </div>
    <div class="col-md-6">
        <em>BTC inside</em>
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/vKtLz_cswCc?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
        </div>
        <small>&copy; Antoine Paris</small>
    </div>
<div class="clearfix"></div>


	<strong class="aller big uppercase">
	Alors, n'attends plus et viens prolonger tes vacances avec nous, emm&egrave;ne ton short, tes crampons, tes maillots et laisse toi aller, on va bien s'occuper de toi  !<br />&Agrave; bient&ocirc;t !  
	</strong>
	</p>