<?php

$mapper=new Default_Model_TournoiMapper();

$all=$mapper->execQuery("select * from tournoi order by nom, prenom",[]);


$this->headLink()->prependStylesheet('/_css/styles.css');

$this->headLink()->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css')->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/7.0.0/css/bootstrap-slider.css')
->appendStylesheet('/_css/css/flag-icon.css')->appendStylesheet ( '/_js/lib/bootstrap-modal/css/bootstrap-modal.css' )->appendStylesheet ( '/_js/lib/bootstrap-modal/css/bootstrap-modal-bs3patch.css' )->appendStylesheet ( '/_js/pnotify.custom.min.css' );
;
$this->headScript()->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/7.0.0/bootstrap-slider.min.js')->appendFile ( '/_js/lib/bootstrap-modal/js/bootstrap-modal.js' )->appendFile ( '/_js/lib/bootstrap-modal/js/bootstrap-modalmanager.js' )->appendFile ( '/_js/lib/ajaxForm.js' )->appendFile ( '/_js/pnotify.custom.min.js' )
?>

<aside class="col-xs-3" id="aside-panel">
<header>
<h1>Bornes to Catch</h1>
<time class="when"><span class="sav">20/21 Ao&ucirc;t 2016</span><span class="fr" style="display:none">20/21 Ao&ucirc;t 2016</span><span class="uk" style="display:none">Aug. 20 &amp; 21<sup>st</sup><br />2016</span></time>
<p class="lieu">Saint-Ferreol (74) <span class="uk" style="display:none">- France</span></p>
</header>



<div class="clearfix"></div>
<nav class="navbar navbar-default text-center" style="background:transparent; border:none;">
  <div class="col-xs-8 col-xs-offset-2">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
  
    </div>

    


    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="#tournoi" id="tounoi-anchor">Le Tournoi</a></li> -->
         <li class="listeInscrits"><span class="sav">Y'a </span><span class="fr" style="display:none">D&eacute;j&agrave; </span><span class="uk" style="display:none">Already</span> <?php  echo count($all)-1 ?> <span class="sav">monchus d'inscrits</span><span class="fr" style="display:none">personnes inscrites</span><span class="uk" style="display:none"> subscribers</span><br />
        <a href="#" id="listeInscrits"><span class="sav">Voir la liste</span><span class="fr" style="display:none">Voir la liste</span><span class="uk" style="display:none">See the list</span></a>
        </li>
        <script>$('#listeInscrits').bind('click', function(e){
        	$('#listeModal').modal();
            });</script>
      </ul>
     
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

</aside>
<p style="text-align:center; font-size:40px;position:absolute;top:50%; transform:translateY(-50%);width:100%">

OUPS !<br />

On fait juste une petite maintenance sur le site.<br />

Sois patient !

</p>

<section id="cont" class="col-xs-9 col-xs-offset-3" style=" background:transparent;position:absolute;">




</section>

<div class="clearfix"></div>

<?php  echo $this->Partial("listejoueurs.phtml",['all'=>$all]);?>