<h2>Le &laquo; Bornes to Catch &raquo;, que c'est ?</h2>
	<p><strong>Adi&ocirc; don' !</strong><br />
	&Ccedil;a va ou bien ?<br />
	Les Dahultimate sont fiers de te pr&eacute;senter la troisi&egrave;me &eacute;dition de leur d&eacute;sormais connu tournoi 100% de la Yaute, le <strong>Bornes to Catch</strong> qui aura lieu le week-end du 18/19 ao&ucirc;t 2018.<br />
	Viens don' profiter de la douceur de l'&eacute;t&eacute; au c&oelig;ur de nos montagnes et au milieu des praz, et participe &agrave; la nouvelle &eacute;dition de notre tournoi <em>&laquo; sap&eacute; &raquo;</em>.<br />Que tu sois un gaillafant, une niougne, un d&eacute;capadiot ou bien plut&ocirc;t le dieu du disque, rejoins-nous, ne t'inqui&egrave;te pas tu ne te feras pas arsouiller, ici on sait recevoir les monchus ! 
	<br /><br />
        <strong>Nous avons tenu compte de toutes tes remarques de l'ann&eacute;e derni&egrave;re, cette &eacute;dition va arsouiller grave !</strong>
        
        </p>
	<p class="text-center">
        <img src="/medias/btc-2017.jpg" class="img-responsive" alt="" />
        </p>
	<div class="col-md-8 col-xs-12" style="padding-left:0">
	<h3>Ouc&eacute; ?</h3>
	<p>
	Le tournoi aura lieu &agrave; Saint-Ferreol, au pied du massif des Bornes, au bout du lac d'Annecy.<br />Tu viens, tu te poses, et pis c'est tout !<br />Parce que tout y est &agrave; c&ocirc;t&eacute; : les terrains, le camping et la salle pour y faire la f&ecirc;te !
	<br />C'est y pas beau, pas ?<br /> Tu vas pouvoir mouiller la meule sans souci si tu le souhaites et ramper sans encombre jusqu'&agrave; ta tente !<br />Mais tu peux aussi venir avec ta petite famille profiter de l'air vivifiant des montagnes.<br />  
	</p>

	<h3>Formule</h3>
	<ul class="list-group col-lg-8 col-md-12 col-xs-12">
		<li class="list-group-item">Tournoi <em>&laquo; sap&eacute; &raquo;</em> n'en loose coed</li>
		<li class="list-group-item">8 &eacute;quipes</li>
		<li class="list-group-item">2 poules de 4 le premier jour sur deux terrains</li>
		<li class="list-group-item">des matchs de classements le dimanche</li>
	</ul>
	<div class="clearfix"></div>
	<h3>Kombienc&eacute; ?</h3>

	
	<ul class="list-group col-lg-8 col-md-12 col-xs-12">
	 <li class="list-group-item active"><strong>Formule "tout compris" (hors boissons) <?php echo PRIX_JOUEUR?> &euro; incluant :</strong></li>
	 <li class="list-group-item">La soir&eacute;e de bienvenue avec son gorgeon de gn&ocirc;le et de quoi grailler</li>
	 <li class="list-group-item">Le petit d&eacute;jeuner du samedi et du dimanche  </li>
	 <li class="list-group-item">Le d&eacute;jeuner du samedi et du dimanche </li>
	 <li class="list-group-item">L'ap&eacute;ro pack du samedi soir </li>
	 <li class="list-group-item">Le repas savoyard du samedi soir </li>
	 <li class="list-group-item">... et plein de surprises </li>
	
	</ul>
<div class="clearfix"></div>
	
	<p>
	Tu peux aussi venir accompagn&eacute; ou n'en tant qu'invit&eacute; pour te payer un peu de bon temps avec nous, il ne t'en co&ucirc;tera que <?php  echo PRIX_NONJOUEUR ?> &euro; comprenant presque tout ce qui est list&eacute; ci-dessus.<br />
	Les croets sont bienvenues, et comme y graillent moins que les grands, le prix est de <?php  echo PRIX_ENFANT?> &euro;. 
	
	
	</p>
	
	<div class="clearfix"></div>
	
	</div>
	
	<div class="col-md-4 col-xs-12 img-thumbnail">
	
	<?php  echo $this->partial('index/map.phtml');?>
	
	
	</div>
	<div class="clearfix"></div>
	<p>
            <strong>Si tu h&eacute;sites encore, va don' voir l'album de l'ann&eacute;e derni&egrave;re c'est <a href="<?php echo BTC_PHOTO_LINK ?>" target="_blank" style="color:#9b1a15"><em class="fa fa-picture-o"></em> ici</a>.</strong>
            <br /><br />
    </p>
<p>
    <strong>Encore un doute ?</strong>

</p>
<div class="col-md-6">
    <em>L'universe point de la finale 2017.</em>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/P9u8NpPehYk?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    </div>
    <small>&copy; Clément Quartier</small>

</div>
<div class="col-md-6">
    <em>BTC inside</em>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/vKtLz_cswCc?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    </div>
    <small>&copy; Antoine Paris</small>
</div>
<div class="clearfix"></div>
	<strong class="aller big uppercase">
	Alors, n'attends plus et viens prolonger tes vacances avec nous, emm&egrave;ne tes cuissettes, tes grolles, tes liquettes et laisse toi faire, on va te cocoler  !  <br />Allez, Arvi pa !
	</strong>
	</p>