	<h2>What is the &laquo; Bornes to Catch &raquo; ?</h2>
	<p><strong>Hi !</strong><br />
	How are you ?<br />
	The Dahultimate team is proud to present your the third edition of their famous tournament, 100% made in Haute-Savoie, the <strong>Bornes to Catch</strong> which will take place the 18 and 19th of august 2018.<br />
	Come to visit us and take the most of the summer in the middle of our montains and our landscape, and take part of the new edition of our Hat tournament.<br />   
	Whether you're clumsy or Brodie's god, please join-us, don't worry, you'll receive a warm welcome, we know how to take care of our guests !
        <br />
        <br />
         <strong>We have considered all your remarks concerning last year to offer you an even more overwhelming and exciting experience !</strong>
	</p>

        <p class="text-center">
        <img src="/medias/btc-2017.jpg" class="img-responsive" alt="" />
        </p>
        
	<div class="col-md-8 col-xs-12" style="padding-left:0">
	<h3>Where will it take place  ?</h3>
	<p>
	At Saint-Ferreol, a small village at the foot of the Bornes moutains, located to the end of the Lake Annecy.<br />Just come and enjoy, everything is at hand  :<br />
	the fields, the camping, and the place for the party !
	<br />Isn't it great ?<br /> 
	You can party all night and go back to your tent without mishap, event if you're plastered !<br />
	But you can come with your familly too to take the most of the pure air of the mountains.<br />  
	</p>

	<h3>Tournament's infos </h3>
	<ul class="list-group col-md-6 col-xs-12">
		<li class="list-group-item">Loose coed Hat tournament</li>
		<li class="list-group-item">2 fields</li>
		<li class="list-group-item">8 teams</li>
		<li class="list-group-item">2 groups of 4 the first day</li>
		<li class="list-group-item">classification matches on Sunday</li>
	</ul>
	<div class="clearfix"></div>
	<h3>How much is it ?</h3>

	
	<ul class="list-group col-md-6 col-xs-12">
	 <li class="list-group-item active"><strong>"All inclusive" formula (drinks excluded) of <?php echo PRIX_JOUEUR?> &euro; including :</strong></li>
	 <li class="list-group-item">The welcome party with a shot of our local "gn&ocirc;le" and all you need to eat</li>
	 <li class="list-group-item">Saturday and Sunday breakfasts</li>
	 <li class="list-group-item">Saturday and Sunday meals</li>
	 <li class="list-group-item">The aperitif pack of Saturday evening</li>
	 <li class="list-group-item">The "Savoyard" dinner of Saturday evening</li>
	 <li class="list-group-item">... and many other surprises</li>
	
	</ul>
<div class="clearfix"></div>
	
	<p>
	You can also come together with your friend, lover, family or as a guest to spend a fantastic week-end with us, it's only <?php echo PRIX_NONJOUEUR?> &euro;.<br />
	Children are welcome, and as they eat (and drink) less than adults, the price is <?php echo PRIX_ENFANT?> &euro; 
	
	</p>
	
	<div class="clearfix"></div>
	
	</div>
	
	<div class="col-md-4 col-xs-12 img-thumbnail">
	
	<?php  echo $this->partial('index/map.phtml');?>
	
	
	</div>
	<div class="clearfix"></div>
	<p>
             <strong>Still wondering why you should join us ? Just take a look at last year's photo album<a style="color:#9b1a15" href="<?php echo BTC_PHOTO_LINK ?>" target="_blank"><em class="fa fa-picture-o"></em> here</a>.</strong>
    </p>
    <p>
        <strong>Still not convinced ?</strong>

    </p>
    <div class="col-md-6">
        <em>The universe  point of the 2017 final.</em>
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/P9u8NpPehYk?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
        </div>
        <small>&copy; Clément Quartier</small>

    </div>
    <div class="col-md-6">
        <em>BTC inside</em>
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/vKtLz_cswCc?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
        </div>
        <small>&copy; Antoine Paris</small>
    </div>
    <div class="clearfix"></div>
            
	<strong class="aller big uppercase">
	Don't hesitate, join us, bring your short, your shoes and your shirts and just enjoy, we will take great care of you !<br />See you soon !
	</strong>
	</p>