<?php
/**
 * Created by PhpStorm.
 * User: Tcho
 * Date: 15/08/2018
 * Time: 22:54
 */


?>

<div class="container">
    <div>
        <h1 class="text-center text-uppercase"
            style="text-align:center;font-size:61px; color:#9b1a15; border-bottom:15px;width:100%;text-transform: uppercase">
            <?php
            echo($this->team->__get('nom'));

            ?>

        </h1>


        <ul class="list-group" style="list-style: none">

            <?php
            usort($this->players, function ($a, $b) {

                return strtolower($a['nom']) > strtolower($b['nom']) ? 1 : -1;

            });

            foreach ($this->players as $player) :
                ?>

                <li class="list-group-item text-center"
                    style="font-size:16px; border:none;list-style: none;font-weight: bold; text-align:center;">
                    <?php echo ucfirst($player['prenom']); ?>  <?php echo strtoupper($player['nom']); ?>
                    / <?php echo strtoupper($player['club']); ?>

                </li>


            <?php endforeach; ?>
            <div class="clearfix"></div>

        </ul>
        <div style="text-align:center">


            <p class="col-md-8" style="font-size:14px;line-height:150px;font-weight: bold">

                <img src="http://bornestocatch.dahultimate.com/medias/logo-mail-tournoi.png" style="max-height: 100px;"
                     align="middle"/>
                Bornes 2B3 - 18/19 Août 2018


            </p>

        </div>

    </div>
</div>
