<?php  echo $this->docType(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
	<table border="0" cellpadding="0" cellspacing="0" width="960">
		<tr>
			<td align="center" valign="bottom"><img
				src="<?php  echo $this->layout()->logo?>" alt="Dahultimates"></td>

		

			<td style="padding-left:40px" valign="bottom">

   
   
   
    <?php echo $this->layout()->content?>

 </td>
		</tr>

	</table>
</body>
</html>