<?php
echo $this->docType();
?>

<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
 <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>

    <?php echo $this->headScript() ?>
        
<link rel="stylesheet" href="/_css/styles.css" type="text/css" />


<script>


$(document).ready(function(){

	$('#langTab').affix({offset:{top:50}})
	
});


</script>


</head>
<body class="current mobile">
<header class="affix-top">

<svg id="dahuLogo" data-name="Calque 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 38 31" class="col-xs-4" style="position:absolute; bottom:0; left:-10px; max-height:100px;"  >
  <circle id="soleil" cx="22.3" cy="15.7" r="12.2" style="fill: #fdce7d"/>
  <g id="dahu">
    <g id="dahuTitre">
      <path d="M20.8,1h0.8a1.7,1.7,0,0,1,1.2.4,1.3,1.3,0,0,1,.4,1,1.5,1.5,0,0,1-.4,1.1,1.8,1.8,0,0,1-1.3.4H20.8V1Zm0.3,2.6h0.4a1.1,1.1,0,0,0,1.2-1.2,1,1,0,0,0-1.2-1.1H21.2V3.6Z" transform="translate(0.5 -1)" style="fill: #fdce7d"/>
      <path d="M24.1,3.2L23.6,4H23.2l1.5-2.6h0.4l0.4,3H25.2v-1Zm1-.1V2.2c0-.2,0-0.4,0-0.6h0l-0.2.5-0.4.8Z" transform="translate(0.5 -1)" style="fill: #fdce7d"/>
      <path d="M27.3,2L26.9,3.1l1.3,0.6,0.5-1.1L29,2.7,27.8,5.4l-0.4-.2L28,4l-1.3-.6L26.2,4.7l-0.3-.2L27,1.8Z" transform="translate(0.5 -1)" style="fill: #fdce7d"/>
      <path d="M30.2,3.5l-1,1.4a0.7,0.7,0,0,0,0,1.1,0.8,0.8,0,0,0,1.1-.4l1-1.4,0.3,0.2-1,1.4a1.1,1.1,0,0,1-1.6.4,1,1,0,0,1-.1-1.6l1-1.4Z" transform="translate(0.5 -1)" style="fill: #fdce7d"/>
      <path d="M32.5,5.2l0.3,0.3L30.9,7.2l0.9,0.9-0.2.2L30.4,7.2Z" transform="translate(0.5 -1)" style="fill: #fdce7d"/>
      <path d="M33.9,7.2l-0.5-.7,0.2-.2L34.9,8l-0.2.2-0.5-.7L32.1,9l-0.2-.3Z" transform="translate(0.5 -1)" style="fill: #fdce7d"/>
      <path d="M35.4,8.8l-2.5,1.5L32.7,10l2.5-1.5Z" transform="translate(0.5 -1)" style="fill: #fdce7d"/>
      <path d="M35.3,12.5l1.1-.5H33.8V11.9l1.1-.9,0.9-.7h0l-1.2.4-1.2.4V10.7L36,9.8l0.2,0.4-1.1,1-0.8.6h2.5l0.2,0.4-2.6,1.2V13.1Z" transform="translate(0.5 -1)" style="fill: #fdce7d"/>
      <path d="M35.3,14.1L34.4,14V13.6l3,0.5v0.4L34.7,16V15.6l0.8-.4v-1ZM35.7,15l0.8-.4,0.5-.2H36.5l-0.9-.2V15Z" transform="translate(0.5 -1)" style="fill: #fdce7d"/>
      <path d="M37.2,16.5V15.6h0.3v2.1H37.2V16.9H34.7V16.5h2.5Z" transform="translate(0.5 -1)" style="fill: #fdce7d"/>
      <path d="M35.7,19.7l0.2-1.1-1-.2-0.2,1.2H34.3L34.6,18l2.9,0.4L37.2,20H36.9l0.2-1.2H36.2L36,19.7H35.7Z" transform="translate(0.5 -1)" style="fill: #fdce7d"/>
    </g>
    <path d="M18.1,13.9a6.1,6.1,0,0,1-1,3.3l-3.7-2.5a1.2,1.2,0,0,1-.2-1.6c-0.5.1-2,1.8-.1,2.4a9.3,9.3,0,0,0,.1,5.3l0.4,0.5a5.7,5.7,0,0,1,.3-3.5l2.8,3.2a16,16,0,0,1-1,3.3L16,24.6c1-1.6,3.1-6.4,3-9.8Z" transform="translate(0.5 -1)" style="fill: #9b1a15"/>
    <path d="M17.4,12.8c-0.9-2-3.6-5.4-4.9-5.9s-3.6-.4-2.7,3.4c-0.9-1.3-1-3.9.8-4.9s5.1-.2,8.5,5.9A2.9,2.9,0,0,1,17.4,12.8Z" transform="translate(0.5 -1)" style="fill: #baab9e"/>
    <path d="M22.2,10.8c-0.5-1.5-2.5-7.1-4.3-8.1a2.5,2.5,0,0,0-3.5,1.1,4.5,4.5,0,0,0,0,2.8c-0.1-1.1.1-2.9,1.4-3.2s2.7,1.5,4.3,7.7A3,3,0,0,0,22.2,10.8Z" transform="translate(0.5 -1)" style="fill: #baab9e"/>
    <path d="M21,16.7c-0.1.6-.2,2.2,1.5,2.4a2.2,2.2,0,0,1-.4-2.4H21Z" transform="translate(0.5 -1)" style="fill: #1d1d1b"/>
    <g id="bouche">
      <path d="M22,15.8l1.8-.8a0.3,0.3,0,0,1,.4.1l0.2,0.5a0.3,0.3,0,0,1-.1.4l-1.8.8a0.3,0.3,0,0,1-.4-0.1l-0.2-.5A0.3,0.3,0,0,1,22,15.8Z" transform="translate(0.5 -1)" style="fill: #9e6e39"/>
      <path d="M24.2,15.6a0.2,0.2,0,0,1-.1.3h0l-1.5.7H22.3l-0.2-.3a0.2,0.2,0,0,1,.1-0.3h0l1.5-.7h0.3Z" transform="translate(0.5 -1)" style="fill: #fff"/>
      <line x1="22.5" y1="15.4" x2="24.7" y2="14.4" style="fill: none;stroke: #1d1d1b;stroke-miterlimit: 10;stroke-width: 3px"/>
      <line x1="23.4" y1="14.5" x2="23.8" y2="15.3" style="fill: none;stroke: #1d1d1b;stroke-miterlimit: 10;stroke-width: 3px"/>
      <line x1="23.1" y1="14.6" x2="23.5" y2="15.5" style="fill: none;stroke: #1d1d1b;stroke-miterlimit: 10;stroke-width: 3px"/>
      <line x1="22.8" y1="14.8" x2="23.2" y2="15.7" style="fill: none;stroke: #1d1d1b;stroke-miterlimit: 10;stroke-width: 3px"/>
      <line x1="24.1" y1="14.2" x2="24.5" y2="15" style="fill: none;stroke: #1d1d1b;stroke-miterlimit: 10;stroke-width: 3px"/>
      <line x1="23.8" y1="14.3" x2="24.2" y2="15.2" style="fill: none;stroke: #1d1d1b;stroke-miterlimit: 10;stroke-width: 3px"/>
      <path d="M24.4,15.6l-0.2-.5a0.3,0.3,0,0,0-.4-0.2h0l-1.8.8a0.3,0.3,0,0,0-.2.4h0l0.2,0.5a0.3,0.3,0,0,0,.4.2h0l1.8-.8a0.3,0.3,0,0,0,.1-0.4h0Zm-0.3.3-1.5.7H22.3l-0.2-.3a0.2,0.2,0,0,1,.1-0.3h0l1.5-.7h0.3l0.2,0.3a0.2,0.2,0,0,1-.1.3h0Z" transform="translate(0.5 -1)" style="fill: #9b1a15"/>
    </g>
    <path d="M18.2,13.4a1.4,1.4,0,0,0-1.9,1.1A1.3,1.3,0,0,0,18.2,13.4Z" transform="translate(0.5 -1)" style="fill: #9b1a15"/>
    <path d="M24,11a1.4,1.4,0,0,0-2.1.8A1.3,1.3,0,0,0,24,11Z" transform="translate(0.5 -1)" style="fill: #9b1a15"/>
    <path d="M17.4,12.8a3.7,3.7,0,0,1,4.8-2c0.6,1.5,2.1,5.2.1,6.1S17.9,14.3,17.4,12.8Z" transform="translate(0.5 -1)" style="fill: #9b1a15"/>
    <path d="M18.3,12.7H18.1a1.4,1.4,0,0,1,.5-0.6v0.2A1,1,0,0,0,18.3,12.7Z" transform="translate(0.5 -1)" style="fill: #1d1d1b"/>
    <path d="M21,11.3V11.1a1.4,1.4,0,0,1,.8.1v0.2H21Z" transform="translate(0.5 -1)" style="fill: #1d1d1b"/>
    <path d="M22,16.6h0Z" transform="translate(0.5 -1)" style="fill: #1d1d1b"/>
    <path d="M22.3,16.5h0.1V16.1H22.3v0.2h0v0.2h0Z" transform="translate(0.5 -1)" style="fill: #1d1d1b"/>
    <g id="oeil_droit" data-name="oeil droit">
      <circle cx="23.2" cy="12.3" r="1" style="fill: #fff"/>
      <circle cx="22.7" cy="12.8" r="0.2" style="fill: #1d1d1b"/>
    </g>
    <g id="oeil_gauche" data-name="oeil gauche">
      <circle cx="19.5" cy="13.7" r="1" style="fill: #fff"/>
      <circle cx="19.8" cy="13" r="0.2" style="fill: #1d1d1b"/>
    </g>
  </g>
  <g id="montagne">
    <polyline points="21.6 30.4 7.6 10.2 0.5 30.9" style="fill: #a8d3cf;stroke: #fff;stroke-miterlimit: 10"/>
    <polygon points="11 20.6 17.2 24 7.6 10.2 5.3 20.9 7 24.7 8.3 19 10.1 21.8 11 20.6" style="fill: #d3ebf0;stroke: #fff;stroke-miterlimit: 10"/>
  </g>
</svg>



<h1>Bornes to catch</h1>
<time><span class="sav">18/19 Ao&ucirc;t 2018</span><span class="fr" style="display:none">18/19 Ao&ucirc;t 2018</span><span class="uk" style="display:none">Aug. 18 &amp; 19<sup>th</sup><br />2018</span></time>
<p class="ou">Saint-Ferreol (74)</p>

<ul class="list-unstyled affix-top" id="langTab">
 <li class="selected"><a data-lang="sav"><span class="flag-icon flag-icon-sav"></span></a></li>
  <li><a data-lang="fr"><span class="flag-icon flag-icon-fr" ></span></a></li>
  <li><a data-lang="uk"><span class="flag-icon flag-icon-gb"></span></a></li>
 
</ul>

</header>

<?php echo $this->layout()->content; ?>

<style>

body, body.current{padding-top:120px;background:#161616 ; font-size:1.2em;}
label, select, input{ font-size:1.2em;}
#cont{padding:0;}

header{
	position:fixed;
	top:0; left:0; 
	z-index:250;
	width:100%;
	background:#161616;

}

header h1, header time, header p{color:white; text-align:center;width:100%;}
h1{
font-size:2.5em;
margin-bottom:10px;
}

header time{
font-Family:AllerBold;
font-size:1.4em;
display:block;
}
.form-control{
height:auto;
}
header p{
font-weight:bold;
font-size:1.2em;
}

.big, h2, h3, legend{
font-size:1.3em;
}

#langTab{

position:absolute;
top:0; right:0;
margin:0;
}

#langTab li{background:#161616; border-right-color:#161616;}

</style>
<script>
$('header').affix({offset:{top:120}});

</script>
</body>
</html>